/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import conjuexamen.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author logan
 */
public class nIngresodatos extends javax.swing.JFrame {
    private servicios  servicio;
    private ResultSet rs;
    private Connection conn;
    
   private int idverificar=0;
   private int  clave;
   private String  tituloexamen;
   private ArrayList<String> arrayAleatorio;
   
    public nIngresodatos() {
        initComponents();
        this.setLocation(400, 50);
        servicio=new servicios();  
        
        
      
       iniciar(); 
    }
    
    public void iniciar(){
        try {
            servicio.conectar("conjugarexamen");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(nIngresodatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        panelNice7 = new org.edisoncor.gui.panel.PanelNice();
        btnGroupAlternativas = new javax.swing.ButtonGroup();
        panelNice4 = new org.edisoncor.gui.panel.PanelNice();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        txtTituloexamen = new org.edisoncor.gui.textField.TextFieldRound();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        panelNice2 = new org.edisoncor.gui.panel.PanelNice();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTituloPr = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        panelNice3 = new org.edisoncor.gui.panel.PanelNice();
        panelNice12 = new org.edisoncor.gui.panel.PanelNice();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtalternativa1 = new org.edisoncor.gui.textField.TextFieldRound();
        txtalternativa2 = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel14 = new javax.swing.JLabel();
        txtalternativa3 = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel15 = new javax.swing.JLabel();
        txtalternativa4 = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel16 = new javax.swing.JLabel();
        txtalternativa5 = new org.edisoncor.gui.textField.TextFieldRound();
        panelNice11 = new org.edisoncor.gui.panel.PanelNice();
        jRBAlternativa4 = new javax.swing.JRadioButton();
        jRBAlternativa2 = new javax.swing.JRadioButton();
        jRBAlternativa1 = new javax.swing.JRadioButton();
        jRBAlternativa5 = new javax.swing.JRadioButton();
        jRBAlternativa3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelNice7Layout = new javax.swing.GroupLayout(panelNice7);
        panelNice7.setLayout(panelNice7Layout);
        panelNice7Layout.setHorizontalGroup(
            panelNice7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelNice7Layout.setVerticalGroup(
            panelNice7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelNice4.setBackground(new java.awt.Color(0, 153, 255));
        panelNice4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNice1.setBackground(new java.awt.Color(255, 255, 255));
        panelNice1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "crear examen", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), java.awt.Color.blue)); // NOI18N
        panelNice1.setBorderColor(new java.awt.Color(0, 0, 204));
        panelNice1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTituloexamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloexamenActionPerformed(evt);
            }
        });
        txtTituloexamen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTituloexamenKeyPressed(evt);
            }
        });
        panelNice1.add(txtTituloexamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 25));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/new.jpg"))); // NOI18N
        jButton3.setText("Nuevo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelNice1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1291628606_configuration_edit.png"))); // NOI18N
        jButton4.setText("Crear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelNice1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 73));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logosa7.jpg"))); // NOI18N
        panelNice1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 110));

        panelNice4.add(panelNice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 110));

        panelNice2.setBackground(new java.awt.Color(255, 255, 255));
        panelNice2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "crear examen", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), java.awt.Color.blue)); // NOI18N
        panelNice2.setBorderColor(new java.awt.Color(0, 102, 255));
        panelNice2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("PREGUNTA:");
        panelNice2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 111, 25));

        txtTituloPr.setColumns(20);
        txtTituloPr.setRows(5);
        txtTituloPr.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane1.setViewportView(txtTituloPr);

        panelNice2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 374, 112));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logosa7.jpg"))); // NOI18N
        panelNice2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 130));

        panelNice4.add(panelNice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, 500, -1));

        panelNice3.setBackground(new java.awt.Color(255, 255, 255));
        panelNice3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "crear examen", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), java.awt.Color.blue)); // NOI18N
        panelNice3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNice12.setBackground(new java.awt.Color(255, 255, 255));
        panelNice12.setBorderColor(new java.awt.Color(0, 102, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("a)");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("b)");

        txtalternativa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalternativa1ActionPerformed(evt);
            }
        });
        txtalternativa1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtalternativa1KeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("c)");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("d)");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("e)");

        javax.swing.GroupLayout panelNice12Layout = new javax.swing.GroupLayout(panelNice12);
        panelNice12.setLayout(panelNice12Layout);
        panelNice12Layout.setHorizontalGroup(
            panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNice12Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtalternativa1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelNice12Layout.createSequentialGroup()
                        .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtalternativa2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtalternativa3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtalternativa4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(panelNice12Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtalternativa5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelNice12Layout.setVerticalGroup(
            panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalternativa1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalternativa2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalternativa3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalternativa4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalternativa5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelNice3.add(panelNice12, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 24, 217, 219));

        btnGroupAlternativas.add(jRBAlternativa4);
        jRBAlternativa4.setForeground(new java.awt.Color(0, 0, 255));

        btnGroupAlternativas.add(jRBAlternativa2);
        jRBAlternativa2.setForeground(new java.awt.Color(0, 0, 255));

        btnGroupAlternativas.add(jRBAlternativa1);
        jRBAlternativa1.setForeground(new java.awt.Color(0, 0, 255));

        btnGroupAlternativas.add(jRBAlternativa5);
        jRBAlternativa5.setForeground(new java.awt.Color(0, 0, 255));

        btnGroupAlternativas.add(jRBAlternativa3);
        jRBAlternativa3.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout panelNice11Layout = new javax.swing.GroupLayout(panelNice11);
        panelNice11.setLayout(panelNice11Layout);
        panelNice11Layout.setHorizontalGroup(
            panelNice11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNice11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBAlternativa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRBAlternativa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRBAlternativa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRBAlternativa4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRBAlternativa5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelNice11Layout.setVerticalGroup(
            panelNice11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jRBAlternativa1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRBAlternativa2)
                .addGap(18, 18, 18)
                .addComponent(jRBAlternativa3)
                .addGap(18, 18, 18)
                .addComponent(jRBAlternativa4)
                .addGap(18, 18, 18)
                .addComponent(jRBAlternativa5)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelNice3.add(panelNice11, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 24, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/telegraph.gif"))); // NOI18N
        panelNice3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 48, -1, -1));

        jButton1.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelNice3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 249, -1, -1));

        jButton2.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SALIR.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelNice3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 249, -1, 41));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logosa7.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        panelNice3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 310));

        panelNice4.add(panelNice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 500, 306));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1_1.JPG"))); // NOI18N
        panelNice4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-17, -130, 540, 940));

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelNice4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelNice4, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtalternativa1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtalternativa1KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtalternativa1KeyPressed

    private void txtalternativa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalternativa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalternativa1ActionPerformed

    private void txtTituloexamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloexamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloexamenActionPerformed

    private void txtTituloexamenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloexamenKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloexamenKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
               elegirAlternativaClave();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          txtTituloexamen.setText(null);
        txtTituloexamen.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
              txtTituloexamen.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    
    public void insertar(){
        try {
            int n1;
                    servicio.consulta("insert into nexamen (tituloexamen,titulopregunta,respclave,altera,alterb,alterc,alterd,altere) value(?,?,?,?,?,?,?,?)");
                   
                    servicio.setString(1, txtTituloexamen.getText());
                    servicio.setString(2, txtTituloPr.getText());
                    servicio.setInt(3, clave);
                    servicio.setString(4, txtalternativa1.getText());
                    servicio.setString(5, txtalternativa2.getText());
                    servicio.setString(6, txtalternativa3.getText());
                    servicio.setString(7, txtalternativa4.getText());
                    servicio.setString(8, txtalternativa5.getText());
                  
                  n1=servicio.executeUpdate();
                  
                if(n1>0){
                   
              JOptionPane.showMessageDialog(null, "se guardo correctamente");
           
              }
               
        } catch (SQLException ex) {
            Logger.getLogger(nIngresodatos.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void elegirAlternativaClave(){
    idverificar=0;
    
        if(jRBAlternativa1.isSelected()==true){
                clave=0;
                idverificar++;
                }
        if(jRBAlternativa2.isSelected()==true){
                clave=1;
                idverificar++;
                }
        if(jRBAlternativa3.isSelected()==true){
                clave=2;
                idverificar++;
                }
        if(jRBAlternativa4.isSelected()==true){
                clave=3;
                idverificar++;
                }
        if(jRBAlternativa5.isSelected()==true){
               clave=4;
                idverificar++;
                }
        
        if(idverificar==0){
            JOptionPane.showMessageDialog(rootPane, "escoja un aalternativa");
        
        }
        if(idverificar!=0){
        insertar();
        }
       
}

public void limpiar(){
    
    txtTituloPr.setText("");
    txtalternativa1.setText("");
    txtalternativa2.setText("");
    txtalternativa3.setText("");
    txtalternativa4.setText("");
    txtalternativa5.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nIngresodatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nIngresodatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nIngresodatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nIngresodatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupAlternativas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRBAlternativa1;
    private javax.swing.JRadioButton jRBAlternativa2;
    private javax.swing.JRadioButton jRBAlternativa3;
    private javax.swing.JRadioButton jRBAlternativa4;
    private javax.swing.JRadioButton jRBAlternativa5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private org.edisoncor.gui.panel.PanelNice panelNice11;
    private org.edisoncor.gui.panel.PanelNice panelNice12;
    private org.edisoncor.gui.panel.PanelNice panelNice2;
    private org.edisoncor.gui.panel.PanelNice panelNice3;
    private org.edisoncor.gui.panel.PanelNice panelNice4;
    private org.edisoncor.gui.panel.PanelNice panelNice7;
    private javax.swing.JTextArea txtTituloPr;
    private org.edisoncor.gui.textField.TextFieldRound txtTituloexamen;
    private org.edisoncor.gui.textField.TextFieldRound txtalternativa1;
    private org.edisoncor.gui.textField.TextFieldRound txtalternativa2;
    private org.edisoncor.gui.textField.TextFieldRound txtalternativa3;
    private org.edisoncor.gui.textField.TextFieldRound txtalternativa4;
    private org.edisoncor.gui.textField.TextFieldRound txtalternativa5;
    // End of variables declaration//GEN-END:variables




}
