/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import conjuexamen.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author logan
 */
public class nMostrar extends javax.swing.JFrame {
    private nobtnerExamen ngetexamen;
    private servicios  servicio;
    private ArrayList<nexamen> examenes;
    
    
   private int idverificar=0;
   private int clave;
  
  
   
   private int idexamen=0;
   private int idpregunta=0;
  
     
    public nMostrar() {
        initComponents();
        //cremos nuestro objeto;
        this.setLocation(400, 50);
        servicio=new servicios();
        examenes=new ArrayList<>();
        ngetexamen=new nobtnerExamen();
        
       examenes=ngetexamen.cargarexamen();
      
    }
    
   

      
    public void mostrar(){
       
           // getexamen();
            txttituloexamen.setText(examenes.get(0).getTituloExamen());
            txtTituloPr.setText(examenes.get(0).getPreguntas().get(0).getTituloPregunta());
            txtalternativa1.setText(examenes.get(0).getPreguntas().get(0).getAlternativas().get(0).getTituloAlternativa());
            txtalternativa2.setText(examenes.get(0).getPreguntas().get(0).getAlternativas().get(1).getTituloAlternativa());
            txtalternativa3.setText(examenes.get(0).getPreguntas().get(0).getAlternativas().get(2).getTituloAlternativa());
            txtalternativa4.setText(examenes.get(0).getPreguntas().get(0).getAlternativas().get(3).getTituloAlternativa());
            txtalternativa5.setText(examenes.get(0).getPreguntas().get(0).getAlternativas().get(4).getTituloAlternativa());
            
            txtid.setText(""+examenes.get(0).getPreguntas().get(0).getId());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        panelNice7 = new org.edisoncor.gui.panel.PanelNice();
        btnGroupAlternativas = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        txttituloexamen = new org.edisoncor.gui.textField.TextFieldRound();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelNice2 = new org.edisoncor.gui.panel.PanelNice();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTituloPr = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panelNice3 = new org.edisoncor.gui.panel.PanelNice();
        panelNice12 = new org.edisoncor.gui.panel.PanelNice();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtalternativa1 = new org.edisoncor.gui.textField.TextFieldRound();
        txtalternativa2 = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel14 = new javax.swing.JLabel();
        txtalternativa3 = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel15 = new javax.swing.JLabel();
        txtalternativa4 = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel16 = new javax.swing.JLabel();
        txtalternativa5 = new org.edisoncor.gui.textField.TextFieldRound();
        panelNice11 = new org.edisoncor.gui.panel.PanelNice();
        jRBAlternativa4 = new javax.swing.JRadioButton();
        jRBAlternativa2 = new javax.swing.JRadioButton();
        jRBAlternativa1 = new javax.swing.JRadioButton();
        jRBAlternativa5 = new javax.swing.JRadioButton();
        jRBAlternativa3 = new javax.swing.JRadioButton();
        txtid = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelNice7Layout = new javax.swing.GroupLayout(panelNice7);
        panelNice7.setLayout(panelNice7Layout);
        panelNice7Layout.setHorizontalGroup(
            panelNice7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelNice7Layout.setVerticalGroup(
            panelNice7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNice1.setBackground(new java.awt.Color(204, 255, 153));
        panelNice1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "crear examen", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), java.awt.Color.blue)); // NOI18N

        txttituloexamen.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));
        txttituloexamen.setCaretColor(new java.awt.Color(0, 0, 204));
        txttituloexamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttituloexamenActionPerformed(evt);
            }
        });
        txttituloexamen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttituloexamenKeyPressed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/First.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Last.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNice1Layout = new javax.swing.GroupLayout(panelNice1);
        panelNice1.setLayout(panelNice1Layout);
        panelNice1Layout.setHorizontalGroup(
            panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txttituloexamen, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNice1Layout.setVerticalGroup(
            panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice1Layout.createSequentialGroup()
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttituloexamen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addComponent(jButton3))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.add(panelNice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 29, -1, -1));

        panelNice2.setBackground(new java.awt.Color(153, 255, 255));
        panelNice2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "crear examen", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), java.awt.Color.blue)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("PREGUNTA:");

        txtTituloPr.setColumns(20);
        txtTituloPr.setRows(5);
        jScrollPane1.setViewportView(txtTituloPr);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/First.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Last.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNice2Layout = new javax.swing.GroupLayout(panelNice2);
        panelNice2.setLayout(panelNice2Layout);
        panelNice2Layout.setHorizontalGroup(
            panelNice2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(545, 545, 545))
            .addGroup(panelNice2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNice2Layout.setVerticalGroup(
            panelNice2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNice2Layout.createSequentialGroup()
                .addGroup(panelNice2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(panelNice2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNice2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNice2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.add(panelNice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 148, 458, 170));

        panelNice3.setBackground(new java.awt.Color(255, 204, 204));
        panelNice3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "crear examen", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), java.awt.Color.blue)); // NOI18N

        panelNice12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("a)");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("b)");

        txtalternativa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalternativa1ActionPerformed(evt);
            }
        });
        txtalternativa1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtalternativa1KeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("c)");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("d)");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setText("e)");

        javax.swing.GroupLayout panelNice12Layout = new javax.swing.GroupLayout(panelNice12);
        panelNice12.setLayout(panelNice12Layout);
        panelNice12Layout.setHorizontalGroup(
            panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNice12Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtalternativa1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelNice12Layout.createSequentialGroup()
                        .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtalternativa2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtalternativa3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtalternativa4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(panelNice12Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtalternativa5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelNice12Layout.setVerticalGroup(
            panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalternativa1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalternativa2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalternativa3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalternativa4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNice12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalternativa5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelNice11.setBackground(new java.awt.Color(0, 153, 204));

        btnGroupAlternativas.add(jRBAlternativa4);
        jRBAlternativa4.setForeground(new java.awt.Color(0, 0, 255));

        btnGroupAlternativas.add(jRBAlternativa2);
        jRBAlternativa2.setForeground(new java.awt.Color(0, 0, 255));

        btnGroupAlternativas.add(jRBAlternativa1);
        jRBAlternativa1.setForeground(new java.awt.Color(0, 0, 255));

        btnGroupAlternativas.add(jRBAlternativa5);
        jRBAlternativa5.setForeground(new java.awt.Color(0, 0, 255));

        btnGroupAlternativas.add(jRBAlternativa3);
        jRBAlternativa3.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout panelNice11Layout = new javax.swing.GroupLayout(panelNice11);
        panelNice11.setLayout(panelNice11Layout);
        panelNice11Layout.setHorizontalGroup(
            panelNice11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNice11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBAlternativa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRBAlternativa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRBAlternativa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRBAlternativa4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRBAlternativa5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelNice11Layout.setVerticalGroup(
            panelNice11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jRBAlternativa1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRBAlternativa2)
                .addGap(18, 18, 18)
                .addComponent(jRBAlternativa3)
                .addGap(18, 18, 18)
                .addComponent(jRBAlternativa4)
                .addGap(18, 18, 18)
                .addComponent(jRBAlternativa5)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SALIR.png"))); // NOI18N
        jButton6.setText("SALIR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1291628526_agt_Utilities.png"))); // NOI18N
        jButton7.setText("MODIFICAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNice3Layout = new javax.swing.GroupLayout(panelNice3);
        panelNice3.setLayout(panelNice3Layout);
        panelNice3Layout.setHorizontalGroup(
            panelNice3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(panelNice12, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelNice11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelNice3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNice3Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNice3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelNice3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNice3Layout.setVerticalGroup(
            panelNice3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice3Layout.createSequentialGroup()
                .addGroup(panelNice3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNice11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelNice3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addComponent(panelNice12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(panelNice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 361, 458, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/azul.jpg"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 550, 760));

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtalternativa1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtalternativa1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtalternativa1KeyPressed

    private void txtalternativa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalternativa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalternativa1ActionPerformed

    private void txttituloexamenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttituloexamenKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttituloexamenKeyPressed

    private void txttituloexamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttituloexamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttituloexamenActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           idexamen--;
        if(idexamen<0){
        idexamen=examenes.size()-1;
        }
    txttituloexamen.setText(examenes.get(idexamen).getTituloExamen());
    actualizarexamen();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           idexamen++;
       if(idexamen>examenes.size()-1){
       idexamen=0;
       }
    txttituloexamen.setText(examenes.get(idexamen).getTituloExamen());
    actualizarexamen();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            idpregunta--;
        if(idpregunta<0){
            idpregunta=examenes.get(idexamen).getPreguntas().size()-1;
        }
        actualizarpregunta();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          idpregunta++;
        if(idpregunta>examenes.get(idexamen).getPreguntas().size()-1){
            idpregunta=0;
        }
        actualizarpregunta();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            int n;
            // TODO add your handling code here:
          elegirAlternativaClave();
          servicio.conectar("conjugarexamen");
          servicio.consulta("update nexamen set tituloexamen=?,titulopregunta=?,respclave=?,altera=?,alterb=?,alterc=?,alterd=?,altere=? where idexamen="+examenes.get(0).getPreguntas().get(idpregunta).getId());
          servicio.setString(1, txttituloexamen.getText());
          servicio.setString(2, txtTituloPr.getText());
          servicio.setInt(3, clave);
          servicio.setString(4, txtalternativa1.getText());
          servicio.setString(5, txtalternativa2.getText());
          servicio.setString(6, txtalternativa3.getText());
          servicio.setString(7, txtalternativa4.getText());
          servicio.setString(8, txtalternativa5.getText());
          
          n=servicio.executeUpdate();
          if(n>0){
          JOptionPane.showMessageDialog(null, "se modifico correctamente");
          }
          
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(nMostrar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         mostrar();
        
    }//GEN-LAST:event_formWindowOpened

    
    public void actualizarpregunta(){

    txttituloexamen.setText(examenes.get(idexamen).getTituloExamen());
    txtTituloPr.setText(examenes.get(idexamen).getPreguntas().get(idpregunta).getTituloPregunta());
    txtalternativa1.setText(examenes.get(idexamen).getPreguntas().get(idpregunta).getAlternativas().get(0).getTituloAlternativa());
    txtalternativa2.setText(examenes.get(idexamen).getPreguntas().get(idpregunta).getAlternativas().get(1).getTituloAlternativa());
    txtalternativa3.setText(examenes.get(idexamen).getPreguntas().get(idpregunta).getAlternativas().get(2).getTituloAlternativa());
    txtalternativa4.setText(examenes.get(idexamen).getPreguntas().get(idpregunta).getAlternativas().get(3).getTituloAlternativa());
    txtalternativa5.setText(examenes.get(idexamen).getPreguntas().get(idpregunta).getAlternativas().get(4).getTituloAlternativa());
    
    txtid.setText(""+examenes.get(idexamen).getPreguntas().get(idpregunta).getId());
   
}
public void actualizarexamen(){
txttituloexamen.setText(examenes.get(idexamen).getTituloExamen());
txtTituloPr.setText(examenes.get(idexamen).getPreguntas().get(0).getTituloPregunta());
txtalternativa1.setText(examenes.get(idexamen).getPreguntas().get(0).getAlternativas().get(0).getTituloAlternativa());
txtalternativa1.setText(examenes.get(idexamen).getPreguntas().get(0).getAlternativas().get(1).getTituloAlternativa());
txtalternativa1.setText(examenes.get(idexamen).getPreguntas().get(0).getAlternativas().get(2).getTituloAlternativa());
txtalternativa1.setText(examenes.get(idexamen).getPreguntas().get(0).getAlternativas().get(3).getTituloAlternativa());
txtalternativa1.setText(examenes.get(idexamen).getPreguntas().get(0).getAlternativas().get(4).getTituloAlternativa());

txtid.setText(""+examenes.get(idexamen).getPreguntas().get(0).getId());
}    
    
    
     
public void elegirAlternativaClave(){
    idverificar=0;
    
        if(jRBAlternativa1.isSelected()==true){
                clave=0;
                idverificar++;
                }
        if(jRBAlternativa2.isSelected()==true){
                clave=1;
                idverificar++;
                }
        if(jRBAlternativa3.isSelected()==true){
                clave=2;
                idverificar++;
                }
        if(jRBAlternativa4.isSelected()==true){
                clave=3;
                idverificar++;
                }
        if(jRBAlternativa5.isSelected()==true){
               clave=4;
                idverificar++;
                }
        
        if(idverificar==0){
            
            clave=examenes.get(0).getPreguntas().get(idpregunta).getCalt();
        
        }
       
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupAlternativas;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRBAlternativa1;
    private javax.swing.JRadioButton jRBAlternativa2;
    private javax.swing.JRadioButton jRBAlternativa3;
    private javax.swing.JRadioButton jRBAlternativa4;
    private javax.swing.JRadioButton jRBAlternativa5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private org.edisoncor.gui.panel.PanelNice panelNice11;
    private org.edisoncor.gui.panel.PanelNice panelNice12;
    private org.edisoncor.gui.panel.PanelNice panelNice2;
    private org.edisoncor.gui.panel.PanelNice panelNice3;
    private org.edisoncor.gui.panel.PanelNice panelNice7;
    private javax.swing.JTextArea txtTituloPr;
    private org.edisoncor.gui.textField.TextFieldRound txtalternativa1;
    private org.edisoncor.gui.textField.TextFieldRound txtalternativa2;
    private org.edisoncor.gui.textField.TextFieldRound txtalternativa3;
    private org.edisoncor.gui.textField.TextFieldRound txtalternativa4;
    private org.edisoncor.gui.textField.TextFieldRound txtalternativa5;
    private javax.swing.JLabel txtid;
    private org.edisoncor.gui.textField.TextFieldRound txttituloexamen;
    // End of variables declaration//GEN-END:variables

}
